apiVersion: v1
kind: Service
metadata:
  name: brain-tumor-service
spec:
  type: NodePort
  selector:
    app: brain-tumor  # This should match the label in the deployment
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007
